## Equal Weight Strategy

In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf
import math

## Load the Stocks' List

In [3]:
tickers = pd.read_csv('top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

## Load the stocks last Close Price & Market Cap

In [9]:
def fetch_market_cap(ticker_list):
    data = yf.download(ticker_list, period='1d', group_by='ticker', auto_adjust=False)
    
    stocks_data = []
    failed = []

    for ticker in ticker_list:
        try:
            if ticker not in data or data[ticker].empty:
                failed.append(ticker)
                continue

            latest_price = data[ticker]['Close'].iloc[-1]
            market_cap = yf.Ticker(ticker).info.get("marketCap", None)

            if pd.isna(latest_price) or market_cap is None:
                failed.append(ticker)
                continue

            stocks_data.append({
                "Ticker": ticker,
                "Market Cap": market_cap,
                "Latest Price": latest_price,
            })

        except Exception:
            failed.append(ticker)
            continue

    print("Failed tickers:", failed)
    return pd.DataFrame(stocks_data)       
    

tickers_list = tickers["Ticker"].values.tolist()
df = fetch_market_cap(tickers_list)
df.head()

[********************* 44%                       ]  22 of 50 completed$TATAMOTORS.NS: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
[*********************100%***********************]  50 of 50 completed

1 Failed download:
['TATAMOTORS.NS']: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted")
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

Failed tickers: ['TATAMOTORS.NS']

         Ticker      Market Cap  Latest Price
0   RELIANCE.NS  17796553506816   1315.099976
1        TCS.NS   8946083430400   2472.600098
2   HDFCBANK.NS  12233024208896    794.700012
3       INFY.NS   5166748663808   1276.800049
4  ICICIBANK.NS   9675494916096   1351.099976

In [8]:
df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  17796553506816   1315.099976
1          TCS.NS   8946083430400   2472.600098
2     HDFCBANK.NS  12233024208896    794.700012
3         INFY.NS   5166748663808   1276.800049
4    ICICIBANK.NS   9675494916096   1351.099976
5   HINDUNILVR.NS   4998776225792   2127.199951
6         SBIN.NS   9817223593984   1063.550049
7   BAJFINANCE.NS   5588183941120    898.950012
8   BHARTIARTL.NS  11396535287808   1870.900024
9          ITC.NS   3741925769216    298.649994
10   KOTAKBANK.NS   3698728632320    371.899994
11    ADANIENT.NS   2899555909632   2129.000000
12          LT.NS   5439662063616   3954.300049
13     HCLTECH.NS   3867459715072   1429.400024
14  ASIANPAINT.NS   2254997028864   2352.399902
15    AXISBANK.NS   4209444126720   1353.599976
16   SUNPHARMA.NS   3964181151744   1652.199951
17       WIPRO.NS   2126520778752    202.970001
18  ULTRACEMCO.NS   3383588028416  11502.000000
19    HDFCLIFE.NS   1335571775488    619.099976
20        ONGC.NS   3617459273728    287.549988
21        NTPC.NS   3745337573376    386.250000
22   POWERGRID.NS   2793436348416    300.350006
23  INDUSINDBK.NS    638009999360    818.900024
24  ADANIGREEN.NS   1787927330816   1085.449951
25       TITAN.NS   3937859796992   4439.299805
26    DIVISLAB.NS   1611394318336   6070.000000
27       TECHM.NS   1271861477376   1435.400024
28      MARUTI.NS   4111127805952  13076.000000
29   COALINDIA.NS   2681403080704    435.100006
30        BPCL.NS   1270965338112    292.950012
31    JSWSTEEL.NS   2941693984768   1204.199951
32     DRREDDY.NS   1029003935744   1235.900024
33  BAJAJFINSV.NS   2856804417536   1788.300049
34  ADANIPORTS.NS   3375991357440   1465.300049
35       CIPLA.NS    978305548288   1211.099976
36   BRITANNIA.NS   1346212855808   5589.000000
37     HAVELLS.NS    799062491136   1273.900024
38    SHREECEM.NS    876762169344  24300.000000
39      GRASIM.NS   1839882829824   2713.000000
40   TATASTEEL.NS   2574064812032    206.389999
41  HEROMOTOCO.NS   1049871056896   5247.000000
42         M&M.NS   3865762594816   3220.199951
43   EICHERMOT.NS   1933915193344   7050.000000
44         IOC.NS   1992224407552    141.080002
45     SBICARD.NS    638571315200    671.049988
46  PIDILITIND.NS   1350066896896   1326.500000
47       DMART.NS   2904149196800   4448.000000
48     HDFCAMC.NS   1090749792256   2546.100098

## Sort the values

In [10]:
df = df.sort_values(by = "Market Cap", ascending = False)
df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  17796553506816   1315.099976
2     HDFCBANK.NS  12233024208896    794.700012
8   BHARTIARTL.NS  11396535287808   1870.900024
6         SBIN.NS   9817223593984   1063.550049
4    ICICIBANK.NS   9675494916096   1351.099976
1          TCS.NS   8946083430400   2472.600098
7   BAJFINANCE.NS   5588183941120    898.950012
12          LT.NS   5439662063616   3954.300049
3         INFY.NS   5166748663808   1276.800049
5   HINDUNILVR.NS   4998776225792   2127.199951
15    AXISBANK.NS   4209444126720   1353.599976
28      MARUTI.NS   4111127805952  13076.000000
16   SUNPHARMA.NS   3964181151744   1652.199951
25       TITAN.NS   3937859796992   4439.299805
13     HCLTECH.NS   3867459715072   1429.400024
42         M&M.NS   3865762594816   3220.199951
21        NTPC.NS   3745337573376    386.250000
9          ITC.NS   3741925769216    298.649994
10   KOTAKBANK.NS   3698728632320    371.899994
20        ONGC.NS   3617459273728    287.549988
18  ULTRACEMCO.NS   3383588028416  11502.000000
34  ADANIPORTS.NS   3375991357440   1465.300049
31    JSWSTEEL.NS   2941693984768   1204.199951
47       DMART.NS   2904149196800   4448.000000
11    ADANIENT.NS   2899555909632   2129.000000
33  BAJAJFINSV.NS   2856804417536   1788.300049
22   POWERGRID.NS   2793436348416    300.350006
29   COALINDIA.NS   2681403080704    435.100006
40   TATASTEEL.NS   2574064812032    206.389999
14  ASIANPAINT.NS   2254997028864   2352.399902
17       WIPRO.NS   2126520778752    202.970001
44         IOC.NS   1992224407552    141.080002
43   EICHERMOT.NS   1933915193344   7050.000000
39      GRASIM.NS   1839882829824   2713.000000
24  ADANIGREEN.NS   1787927330816   1085.449951
26    DIVISLAB.NS   1611394318336   6070.000000
46  PIDILITIND.NS   1350066896896   1326.500000
36   BRITANNIA.NS   1346212855808   5589.000000
19    HDFCLIFE.NS   1335571775488    619.099976
27       TECHM.NS   1271861477376   1435.400024
30        BPCL.NS   1270965338112    292.950012
48     HDFCAMC.NS   1090749792256   2546.100098
41  HEROMOTOCO.NS   1049871056896   5247.000000
32     DRREDDY.NS   1029003935744   1235.900024
35       CIPLA.NS    978305548288   1211.099976
38    SHREECEM.NS    876762169344  24300.000000
37     HAVELLS.NS    799062491136   1273.900024
45     SBICARD.NS    638571315200    671.049988
23  INDUSINDBK.NS    638009999360    818.900024

## Taking Top 10 Stocks as per the market cap

In [11]:
df = df.head(10)
df.reset_index(inplace=True, drop = True)
df

          Ticker      Market Cap  Latest Price
0    RELIANCE.NS  17796553506816   1315.099976
1    HDFCBANK.NS  12233024208896    794.700012
2  BHARTIARTL.NS  11396535287808   1870.900024
3        SBIN.NS   9817223593984   1063.550049
4   ICICIBANK.NS   9675494916096   1351.099976
5         TCS.NS   8946083430400   2472.600098
6  BAJFINANCE.NS   5588183941120    898.950012
7          LT.NS   5439662063616   3954.300049
8        INFY.NS   5166748663808   1276.800049
9  HINDUNILVR.NS   4998776225792   2127.199951